{
  inputs,
  ...
}: {
  imports = [
    ./profiles.nix
    ./fonts.nix
    ./hardware.nix
    ./network.nix
    ./nh.nix
    ./packages.nix
    ./services.nix
    ./stylix.nix
    ./system.nix
    ./user.nix
    ./virtualisation.nix
    ./xdg.nix
    ./fingerprint.nix
    ./NixOS-Sec-Toolbox
    inputs.stylix.nixosModules.stylix
    ./customConf
    ./k3s-single-node.nix
    ./mullvad.nix
    ./netbird.nix
    ./ram.nix
    ./emulateboot.nix
    ./build.nix
  ];
}
